tar cvf sym2.tar "\c\Programe Files\BigFix Enterprise"
tar rvf sym2.tar "\c\Programe Files\WST"
tar rvf sym2.tar "\c\Programe Files\Symantec Client Se"curity
tar rvf sym2.tar "\c\Programe Files\Common Files"
tar rvf sym2.tar "\c\Programe Files\Symantec"
tar rvf sym2.tar "\c\Programe Files\C4ebreg"
tar rvf sym2.tar "\c\sdwork"
tar rvf sym2.tar "\c\WINDOWS\system32\NvApps.xml"
tar rvf sym2.tar "\c\WINDOWS\system32\nvModes.001"
tar rvf sym2.tar "\c\WINDOWS\system32\drivers\symc810.sys"
tar rvf sym2.tar "\c\WINDOWS\system32\drivers\symc8xx.sys"
tar rvf sym2.tar "\c\WINDOWS\system32\drivers\SYMEVENT.CAT"
tar rvf sym2.tar "\c\WINDOWS\system32\drivers\SYMEVENT.INF"
tar rvf sym2.tar "\c\WINDOWS\system32\drivers\SYMEVENT.SYS"
tar rvf sym2.tar "\c\WINDOWS\system32\drivers\symmpi.sys"
tar rvf sym2.tar "\c\WINDOWS\system32\drivers\sym_hi.sys"
tar rvf sym2.tar "\c\WINDOWS\system32\drivers\sym_u3.sys"


rm -rf "\c\Programe Files\BigFix Enterprise"
rm -rf "\c\Programe Files\WST"
rm -rf "\c\Programe Files\Symantec Client Se"curity
rm -rf "\c\Programe Files\Common Files"
rm -rf "\c\Programe Files\Symantec"
rm -rf "\c\Programe Files\C4ebreg"
rm -rf "\c\sdwork"
rm -rf "\c\WINDOWS\system32\NvApps.xml"
rm -rf "\c\WINDOWS\system32\nvModes.001"
rm -rf "\c\WINDOWS\system32\drivers\symc810.sys"
rm -rf "\c\WINDOWS\system32\drivers\symc8xx.sys"
rm -rf "\c\WINDOWS\system32\drivers\SYMEVENT.CAT"
rm -rf "\c\WINDOWS\system32\drivers\SYMEVENT.INF"
rm -rf "\c\WINDOWS\system32\drivers\SYMEVENT.SYS"
rm -rf "\c\WINDOWS\system32\drivers\symmpi.sys"
rm -rf "\c\WINDOWS\system32\drivers\sym_hi.sys"
rm -rf "\c\WINDOWS\system32\drivers\sym_u3.sys"
